BASE_URL = 'https://stellarburgers.nomoreparties.site/'
FORGOT_PASSWORD_URL = BASE_URL + 'reset-password'
LOGIN_PAGE = BASE_URL + 'login'
PROFILE_PAGE = BASE_URL + 'account/profile'
ORDER_HISTORY_URL = BASE_URL + 'account/order-history'
ORDER_FEED = BASE_URL + 'feed'
